import React from 'react';
import { Link } from 'react-router-dom';
import '../stylesheets/legal.css';

export default function Terms() {
    return (
        <div className="legal-container">
            <div className="legal-wrapper">
                {/* Header */}
                <div className="legal-header">
                    <Link to="/" className="back-to-home">
                        <span>←</span> Back to ClipForge
                    </Link>
                    <h1>Terms of Service</h1>
                    <p className="last-updated">Last Updated: January 5, 2026</p>
                </div>

                {/* Content */}
                <div className="legal-content">
                    <section>
                        <h2>1. Acceptance of Terms</h2>
                        <p>
                            By accessing and using ClipForge ("the Service"), you accept and agree to be bound by 
                            the terms and provisions of this agreement. If you do not agree to abide by these terms, 
                            please do not use this Service.
                        </p>
                    </section>

                    <section>
                        <h2>2. Description of Service</h2>
                        <p>
                            ClipForge is a video generation platform that uses AI to create short-form video content. 
                            The Service includes:
                        </p>
                        <ul>
                            <li>AI-generated story content based on selected subreddit styles</li>
                            <li>Text-to-speech narration using ElevenLabs technology</li>
                            <li>Automated subtitle generation and video composition</li>
                            <li>Background video integration</li>
                        </ul>
                    </section>

                    <section>
                        <h2>3. User Accounts</h2>
                        <p>
                            To use certain features of the Service, you must register for an account. You agree to:
                        </p>
                        <ul>
                            <li>Provide accurate and complete information during registration</li>
                            <li>Maintain the security of your password and account</li>
                            <li>Promptly update any changes to your account information</li>
                            <li>Accept responsibility for all activities that occur under your account</li>
                        </ul>
                    </section>

                    <section>
                        <h2>4. User Content</h2>
                        <p>
                            You retain ownership of any content you create using ClipForge. However, by using 
                            the Service, you grant us a non-exclusive, worldwide, royalty-free license to use, 
                            store, and process your content solely for the purpose of providing the Service.
                        </p>
                        <p>
                            You are solely responsible for the content you create and must ensure it:
                        </p>
                        <ul>
                            <li>Does not violate any applicable laws or regulations</li>
                            <li>Does not infringe on any third party's intellectual property rights</li>
                            <li>Does not contain harmful, abusive, or offensive material</li>
                            <li>Does not promote illegal activities or violence</li>
                        </ul>
                    </section>

                    <section>
                        <h2>5. Prohibited Uses</h2>
                        <p>You agree not to use the Service to:</p>
                        <ul>
                            <li>Generate content that promotes hate speech, discrimination, or violence</li>
                            <li>Create deepfakes or misleading content intended to deceive</li>
                            <li>Impersonate other individuals or entities</li>
                            <li>Violate any intellectual property or privacy rights</li>
                            <li>Distribute spam, malware, or other harmful content</li>
                            <li>Attempt to gain unauthorized access to the Service or its systems</li>
                            <li>Use automated systems to access the Service without permission</li>
                        </ul>
                    </section>

                    <section>
                        <h2>6. AI-Generated Content</h2>
                        <p>
                            Content generated by AI through our Service may not always be accurate, appropriate, 
                            or suitable for all purposes. You acknowledge that:
                        </p>
                        <ul>
                            <li>AI-generated content should be reviewed before use</li>
                            <li>We are not responsible for any inaccuracies in AI-generated content</li>
                            <li>You are responsible for ensuring generated content meets your needs and complies with applicable laws</li>
                        </ul>
                    </section>

                    <section>
                        <h2>7. Third-Party Services</h2>
                        <p>
                            ClipForge integrates with third-party services including OpenAI and ElevenLabs. 
                            Your use of these services through ClipForge is subject to their respective 
                            terms of service and privacy policies.
                        </p>
                    </section>

                    <section>
                        <h2>8. Limitation of Liability</h2>
                        <p>
                            TO THE MAXIMUM EXTENT PERMITTED BY LAW, CLIPFORGE AND ITS OPERATORS SHALL NOT BE 
                            LIABLE FOR ANY INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, OR PUNITIVE DAMAGES, 
                            OR ANY LOSS OF PROFITS OR REVENUES, WHETHER INCURRED DIRECTLY OR INDIRECTLY.
                        </p>
                    </section>

                    <section>
                        <h2>9. Indemnification</h2>
                        <p>
                            You agree to indemnify and hold harmless ClipForge and its operators from any 
                            claims, damages, losses, or expenses arising from your use of the Service or 
                            violation of these Terms.
                        </p>
                    </section>

                    <section>
                        <h2>10. Modifications to Terms</h2>
                        <p>
                            We reserve the right to modify these Terms at any time. We will notify users of 
                            significant changes by posting a notice on the Service. Your continued use of 
                            the Service after such modifications constitutes acceptance of the updated Terms.
                        </p>
                    </section>

                    <section>
                        <h2>11. Termination</h2>
                        <p>
                            We may terminate or suspend your account and access to the Service at our sole 
                            discretion, without prior notice, for conduct that we believe violates these 
                            Terms or is harmful to other users, us, or third parties.
                        </p>
                    </section>

                    <section>
                        <h2>12. Contact Information</h2>
                        <p>
                            If you have any questions about these Terms, please contact us at:
                        </p>
                        <p className="contact-info">
                            <strong>Email:</strong> support@clipforge.app
                        </p>
                    </section>
                </div>

                {/* Footer */}
                <div className="legal-footer">
                    <Link to="/privacy">Privacy Policy</Link>
                    <span className="footer-dot">•</span>
                    <Link to="/login">Sign In</Link>
                    <span className="footer-dot">•</span>
                    <Link to="/signup">Create Account</Link>
                </div>
            </div>
        </div>
    );
}

